# Generated by Django 5.1.2 on 2025-01-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganymede', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='musicx',
        ),
    ]
