# Generated by Django 5.1.2 on 2025-01-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganymede', '0003_alter_song_options_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='playlists/'),
        ),
    ]
