# Generated by Django 5.1.2 on 2025-02-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganymede', '0004_playlist_cover_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistcollaborator',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playlistcollaborator',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistcollaborator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlisthistory',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlisthistory',
            name='song',
        ),
        migrations.RemoveField(
            model_name='playlisthistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_artists',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlayHistory',
        ),
        migrations.DeleteModel(
            name='PlaylistCollaborator',
        ),
        migrations.DeleteModel(
            name='PlaylistHistory',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
